### ISSUE TITLE
Provider for google calendar integration

### ISSUE THREAD

**Issue by kkapsner** [kkapsner/keepassxc-mail#1]
Provider for google calendar is widely used and should be considered.

I do not use it... so someone who is interested might try it and give me feedback.

**Comment by pauleve** [comment]
Many many thanks for this awesome extension :-)

I'm using google calendar, and it doesn't seem to work unfortunately.
In Thunderbird, it seems linked to an ill-formed URL of the form "oauth:username@gmail.com"... However, having such an entry in keepassxc does not work.
Let me know how I can debug it (although I'll be able doing it only next week..)

**Comment by pauleve** [comment]
Not sure if that points to something relevant, but after some digging in the source code of calendar extension, the request for the password is done using `Services.logins.findLogins`:
https://github.com/kewisch/gdata-provider/blob/d55f7b4b6d4392cf51508e74431ae42f5abdcb58/src/modules/gdataSession.jsm#L186
https://github.com/mozilla/releases-comm-central/blob/270470d499e96db29be2dcbc097f1b6db87f0534/calendar/base/modules/utils/calAuthUtils.jsm#L461

which doesn't seem to call the add-on...

**Comment by kkapsner** [comment]
OK... seems I have to do some work there... as Google calendar is free I might just create one to test this.

**Comment by kkapsner** [comment]
Please try https://github.com/kkapsner/keepassxc-mail/releases/tag/v0.1.1

**Comment by pauleve** [comment]
It does not seem to work here.. or maybe I'm not using properly. I have an entry with oauth:myemail in keepassxc with the token taken from thunderbird password manager ; then I clear all saved passwords in the thunderbird password manager ; and on restart, Thunderbird asks again for login on google, and store the token in its password manager..

**Comment by kkapsner** [comment]
Oh... I just added support for the oauth setup. Now that I think about it... storing the oauth token in the Thunderbird password manager in plaintext is not that of a good idea...

Will have to dig deeper.

**Comment by kkapsner** [comment]
Please try https://github.com/kkapsner/keepassxc-mail/releases/tag/v0.1.2

The token has to be stored with `oauth://` at the beginning.
