### ISSUE TITLE
Thunderbird 132 is not supported

### ISSUE THREAD

**Issue by rahqbo** [kkapsner/keepassxc-mail#104]
Thunderbird 132 is not supported. Is it planned to update the addon or should I use an older maintained Thunderbird version?

**Comment by johndickinson** [comment]
The release notes for version 1.9 say that 132 is supported - https://github.com/kkapsner/keepassxc-mail/blob/master/releaseNotes.txt
However they are yet to release that version. I guess it needs more work. You could try building from source or wait for the developers to do a release.

**Comment by kkapsner** [comment]
I plan to submit version 1.9 within the next days.

**Comment by bohni** [comment]
1.9 seems to be broken with Thunderbird 128.5.2esr. I had to go back to 1.8

**Comment by kkapsner** [comment]
Which version of KeePassXC are you using?

**Comment by bohni** [comment]
I'm installing my software using winget. KeepassXC 2.7.9 is the version, that gets installed using winget.

**Comment by kkapsner** [comment]
That's really weird... I use Thunderbird 128.5.1esr and KeePassXC 2.7.9 and it's working for me (I'm on Linux though...)

I will test Windows...

**Comment by kkapsner** [comment]
What do you see in the console (Ctrl + Shift + J and select "multi process")?

**Comment by kkapsner** [comment]
OK  -  found the culprit...

**Comment by bohni** [comment]
Thanks for the fast reaction and spending your time on holiday...

**Comment by kkapsner** [comment]
#105 will track the progress on the topic.

**Comment by kkapsner** [comment]
Solved with https://github.com/kkapsner/keepassxc-mail/releases/tag/v1.9.1
