### ISSUE TITLE
[Regression][v1.9] Password no longer found

### ISSUE THREAD

**Issue by martin-rueegg** [kkapsner/keepassxc-mail#105]
Since today's update, no password is found anymore.

## Description
Since today's update, no password is found anymore. Restarted TB and KeePassXC but no avail.

Did not update of KPXC. Password retrieval from Firefox still works.

`Reconnect to Native Messaging` and `Connect to KeePassXC` does not display any error message. But see console log below.

`C:\Program Files\KeePassXC\keepassxc-proxy.exe` is running.

## Console Log
```
[Error ] KeePassXC-Mail - Failed to connect: Unknown error [global.js:41:10](moz-extension://0c273066-5dec-4e0d-8b2c-de23733eaf99/global.js)
2024-12-24 14:27:06.327: Try native application de.kkapsner.keepassxc_mail [main.js:26:11](moz-extension://0c273066-5dec-4e0d-8b2c-de23733eaf99/main.js)
KeePassXC-Mail: Connecting to native messaging host de.kkapsner.keepassxc_mail [client.js:383:13](moz-extension://0c273066-5dec-4e0d-8b2c-de23733eaf99/from-keepassxc-browser/client.js)
KeePassXC-Mail: Server public key: F/Zu/b/iButcqlUekR1j1XdYRQgG/UoFfknPId3eA2A= [keepass.js:426:17](moz-extension://0c273066-5dec-4e0d-8b2c-de23733eaf99/from-keepassxc-browser/keepass.js)
2024-12-24 14:28:11.526: got credential request: 
Object { login: "xxx@example.com", host: "oauth://accounts.google.com", openChoiceDialog: true }
[main.js:26:11](moz-extension://0c273066-5dec-4e0d-8b2c-de23733eaf99/main.js)
2024-12-24 14:28:11.541: Use saved native application de.kkapsner.keepassxc_mail [main.js:26:11](moz-extension://0c273066-5dec-4e0d-8b2c-de23733eaf99/main.js)
KeePassXC-Mail: Connecting to native messaging host de.kkapsner.keepassxc_mail [client.js:383:13](moz-extension://0c273066-5dec-4e0d-8b2c-de23733eaf99/from-keepassxc-browser/client.js)
KeePassXC-Mail: Server public key: beMOcr5ZnrgCnGrbKtfwP1Y9mGlh0xf4bAgseBtWWAU= [keepass.js:426:17](moz-extension://0c273066-5dec-4e0d-8b2c-de23733eaf99/from-keepassxc-browser/keepass.js)
2024-12-24 14:28:11.949: Initialization failed: ReferenceError: compareVersion is not defined
    enableAutomaticReconnect moz-extension://0c273066-5dec-4e0d-8b2c-de23733eaf99/from-keepassxc-browser/keepass.js:789
    initialize moz-extension://0c273066-5dec-4e0d-8b2c-de23733eaf99/main.js:151
[main.js:26:11](moz-extension://0c273066-5dec-4e0d-8b2c-de23733eaf99/main.js)
WebExtensions: ReferenceError: compareVersion is not defined
    enableAutomaticReconnect moz-extension://0c273066-5dec-4e0d-8b2c-de23733eaf99/from-keepassxc-browser/keepass.js:789
    initialize moz-extension://0c273066-5dec-4e0d-8b2c-de23733eaf99/main.js:151
[implementation.js:1401](jar:file:///C:/Users/mdr/AppData/Roaming/Thunderbird/Profiles/gudur4r9.default/extensions/keepassxc-mail@kkapsner.de.xpi!/experiment/implementation.js)
```

## Your Environment
* KeePassXC-mail version used: v1.9
* KeePassXC version: 2.7.9
* Thunderbird version: 128.5.2esr (64-bit)
* Operating system and version: Microsoft Windows [Version 10.0.26100.2605]

**Comment by kkapsner** [comment]
Please downgrade to 1.8 - there is a missing dependency from keepassxc-browser.

**Comment by kkapsner** [comment]
Version 1.9 is already disabled on ATN.

**Comment by kkapsner** [comment]
Issue was introduced by 5892d3a31c79b95de249eb05d6f21c5894eb36d0

**Comment by kkapsner** [comment]
Solved with https://github.com/kkapsner/keepassxc-mail/releases/tag/v1.9.1 - ATN is waiting for validation.

**Comment by martin-rueegg** [comment]
Thank you @kkapsner for your quick fix and the awesome work!

Meanwhile, **if anyone else is affected,** you can downgrade to version 1.8 by opening the `Add-On Manager` in TB, search for `keepass` and add `keepassxc-mail` to TB again. Version 1.9 will be overwritten with version 1.8, unless version 1.9.1 has been published by then. Version 1.9.1 will then be installed once available on ATN.

**Comment by kkapsner** [comment]
I already disabled 1.9 on ATN. Does it still push it to you?

**Comment by martin-rueegg** [comment]
No, but I was just describing how to downgrade to 1.8 after the automatic
update that happened a few minutes before I opened this issue.

**Comment by kkapsner** [comment]
Ah sorry - I misunderstood you. You can also download the xpi file from the release page and import it into thunderbird. Then you have 1.9.1 immediately.
