### ISSUE TITLE
keepassxc-mail makes no connection with KeePassXC

### ISSUE THREAD

**Issue by elysium1962** [kkapsner/keepassxc-mail#106]
Since the update of keepassxc-mail to 1.9  it looks like Thunderbird is not getting any connection to KeePassXC.
## Description

With the previous version of keepassxc-mail when I opened Thunderbird it would not ask for a password, because it was derived from the KeePassXC database. Now everytime I open Thunderbird, I see a dialog asking me for entering the password for Thunderbird account .
## Expected Behaviour

Thunderbird not asking for the account password.
## Current Behaviour

Thunderbird asking for the account password.
## Possible Solution

No idea. Maybe reverse to previous version of keepassxc-mail?
## Steps to Reproduce (for bugs)

1. Open Thunderbird and wait for account password. See below.

![Thunderbird-account-password](https://github.com/user-attachments/assets/e2e0c949-6473-4443-9a6c-32c3b6abfa31)

2. After password, I noticed in the Add-ons of Thunderbird looking at keepassxc-mail that under Options there is no conection with KeepassXC. In the past the key was show here.

![KeePassXC-mail-options](https://github.com/user-attachments/assets/fb84057f-856d-4bb3-bb6b-b873482c461e)
4. When I click Connect to KeePassXC, a dialog from KeePassXC opens and request a unique name. After entering it is stored in the KeePassXC database under security.

## Context

To try to resolve this issue, I removed the Add-on and reinstalled the Add-on. I followed the description at https://github.com/kkapsner/keepassxc-mail and it did not work. I checked the registry and that looks according the description.
## Your Environment

* KeePassXC-mail version used: 1.9
* KeePassXC version: 2.7.9
* Thunderbird version: 128.5.2esr (64 bit)
* Operating system and version: Windows 11 Pro, version 24H2, OS build 26100.2605

**Comment by kkapsner** [comment]
This issue is fixed with 1.9.1 which should be available.
