### ISSUE TITLE
Error 15: No logins found

### ISSUE THREAD

**Issue by kocjs** [kkapsner/keepassxc-mail#12]
### Thank you for doing this addon.

I am trying to set this up, but it does not work. I am getting "Error 15: No logins found" in the thunderbird error console.

### This is how my keepassxc entry looks like.
Title: imap://imap.mail.yahoo.com
username: me@yahoo.com
Password: xxx
url: imap://imap.mail.yahoo.com

### system details
Debian buster, thunderbird 68.7, addon v12

**Comment by kkapsner** [comment]
Please give me a screenshot of the Thunderbird password prompt and of the "browser integration" tab of the entry.

**Comment by kocjs** [comment]
![Screenshot from 2020-04-22 14-09-51](https://user-images.githubusercontent.com/30014316/79960474-f6359180-8474-11ea-9416-71054a542033.png)
![Screenshot from 2020-04-22 14-07-37](https://user-images.githubusercontent.com/30014316/79960479-f897eb80-8474-11ea-954f-8c3b2658a27a.png)
![Screenshot from 2020-04-22 14-05-24](https://user-images.githubusercontent.com/30014316/79960484-f9308200-8474-11ea-9910-03afe3e1aeb4.png)


It seems to connect well.

**Comment by kkapsner** [comment]
The password request if for the smtp server (smtp.mail.yahoo.com) - not imap. If you use the same credentials for that you can add the additional URL smtp://smtp.mail.yahoo.com in the "Browser integration" page.

**Comment by kocjs** [comment]
Even with the above instructions it is not working for me. If I allow the access request noting happens. Then when i try again error 8 appers
![Screenshot from 2020-04-22 20-38-57](https://user-images.githubusercontent.com/30014316/79999533-8bec1380-84ab-11ea-8a61-8a9634c855e1.png)

**Comment by kkapsner** [comment]
That's weird.
Please go to the keepassxc-mail settings and click the two "(re)connect..." buttons.

**Comment by kocjs** [comment]
Thank you for staying on this with me. 

Done as asked, did not help.

![Screenshot from 2020-04-23 07-35-10](https://user-images.githubusercontent.com/30014316/80051183-20379400-8507-11ea-84fe-2d1b63289ae9.png)

I've tried a view more times, the results are not consistent. 
Some times an association window opens, others not. 

There is only one entry, with the addition to smtp:// in the browser integration tap. 

Keepassxc-mail tries to access the entry, visible form the history.
![Screenshot from 2020-04-23 07-35-07](https://user-images.githubusercontent.com/30014316/80051428-a6ec7100-8507-11ea-881c-b4447f452d66.png)

If i try to get messages
 
![Screenshot from 2020-04-23 07-49-26](https://user-images.githubusercontent.com/30014316/80052081-5118c880-8509-11ea-9ef6-cac3b9f2bf42.png)

If i try to send a mail

![Screenshot from 2020-04-23 07-53-27](https://user-images.githubusercontent.com/30014316/80052198-a228bc80-8509-11ea-8c49-2504ac164803.png)

Here the properties tab

![Screenshot from 2020-04-23 08-00-04](https://user-images.githubusercontent.com/30014316/80052509-5c202880-850a-11ea-8003-5c4fa8b9c028.png)


Sometimes the "unreachable code after return statement" appears.

![Screenshot from 2020-04-23 07-57-40](https://user-images.githubusercontent.com/30014316/80052437-32670180-850a-11ea-8031-8ddc1b53565d.png)

**Comment by kocjs** [comment]
I am using the stable appimage.

**Comment by kkapsner** [comment]
The "unreachable code after return statement" is normal. keepassxc-mail uses code from keepassxc-browser to communicate with keepassxc. I just had to disable some functionalities that are not present in Thunderbird.

The association error is weird and I have no clue what's the problem there - especially because sometimes an association window appears and sometimes not...

BUT I noticed a missconfiguation: in keepassxc you have the username kocjso@yahoo.com but in Thunderbird it's only kocjso. These have to match so please change the entry in keepassxc.

**Comment by kocjs** [comment]
Yes, it works now.

Thank you so much

**Comment by kkapsner** [comment]
Great.
