### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by martin-rueegg** [kkapsner/keepassxc-mail#13]
Hi

I've tried to get it running following the instructions in the [README.md](https://github.com/kkapsner/keepassxc-mail/blob/master/README.md). However, when trying to connect to KeePassXC in the Add-On options, nothing happens.

KeePassXC is already using browser integration. I have temporarily enabled all browser types. It's set to use a proxy application, but not a custom one.

I've double checked the Registry entry at (Computer\HKEY_CURRENT_USER\Software\Mozilla\NativeMessagingHosts\de.kkapsner.keepassxc_mail) which is correctly pointing to the json file, which exists. The json file looks exactly like the `org.keepassxc.keepassxc_browser_tor-browser.json` apart from the allowed browser extension and `name`. I guess, all as it is supposed to be.

Do you have any tips for me? Or any additional information/logs I can provide?
Thanks,
Martin.

Windows 10 Home 1903
Thunderbird 68.8.0
keepassxc-mail v0.1.2
KeePassXC 2.5.4

**Comment by kkapsner** [comment]
There should be something in the error console of Thunderbird (Shift + Ctrl + J). Maybe there a hint can be found why it's not working.

Also a screenshot of your browser integration setting pages might help to find the culprit.

**Comment by martin-rueegg** [comment]
Thank you @kkapsner for your quick reply. It was the character encoding of the generated JSON file that caused it not to work!

```
cat (Join-Path -path (get-item env:USERPROFILE).value -childPath AppData\Local\KeePassXC\org.keepassxc.keepassxc_browser_tor-browser.json) |
	%{$_ -replace "keepassxc-browser@keepassxc.org","keepassxc-mail@kkapsner.de"} |
	%{$_ -replace "org.keepassxc.keepassxc_browser","de.kkapsner.keepassxc_mail"} |
	Out-File -filePath (Join-Path -path (get-item env:USERPROFILE).value -childPath AppData\Local\KeePassXC\de.kkapsner.keepassxc_mail.json)
```
created a file on my system, that was UCS-2 LE BOM. The hex representation of the BOM was `FF FE`. 
So when I tried to `Reconnect to Native Messaging` it threw an error that JSON data was invalid at line 1 position 1. :-)

I changed the encoding to UTF-8 (without BOM) and now it works as expected!

Not sure if PowerShell can be instructed to use UTF-8 encoding or the extension can do the conversion if a BOM is present?

Thanks again for your help.
Martin.

**Comment by martin-rueegg** [comment]
PS: I guess once you change the extension to use KeePassXC's original messaging descriptor, this issue becomes obsolete.
(referring https://github.com/keepassxreboot/keepassxc/issues/1683#issuecomment-603077218)

**Comment by kkapsner** [comment]
The extension is not reading the file but the browser - so I cannot change that. But I can add the `-Encoding` parameter to not output the BOM.

**Comment by martin-rueegg** [comment]
Awesome. Can confirm that the additional parameter makes it work also on my system.
