### ISSUE TITLE
multiple reconnections with KeePassXC

### ISSUE THREAD

**Issue by piramiday** [kkapsner/keepassxc-mail#16]
I think I got this extension to work:
1. fresh virtual machine,
2. installed thunderbird, lightning, keepassxc,
3. installed extension,
4. executed thunderbird, connected to KPXC,
5. managed to get passwords with auto-submit,

which seems really great. thanks for coding this!

my current issue is that, after I quit Thunderbird and reopen it, the extension asks me for a new association with KeePassXC (that is, step 4):

![Screenshot at 2020-06-10 10-25-31](https://user-images.githubusercontent.com/48775554/84299187-30322400-ab05-11ea-98aa-9cd582f4f3ed.png)

is this supposed to happen?

also, I would suggest to make the Lightning requirement a bit more explicit -- for example, as another numbered step in your Usage guide, as opposed to some italics after the bullet list.

**Comment by piramiday** [comment]
could you please briefly explain what the two buttons do?
- `Reconnect to Native Messaging`, and
- `Connect to KeePassXC`?

since I had already my passwords in KeePassXC, what I was doing was _just starting Thunderbird and filling in the automatic connection prompt_, as per the screenshot in my first post.
as it turns out, **I should not do that**!

if I reply `Cancel` there, and instead I go in Tools > Add-ons > keepassxc-mail and click on `Connect to KeePassXC`, then I do get a "stable" connection that survives restarts.
(even though the prompt is exactly the same, mind you!)

if I had accepted that initial prompt, then going into Tools > ... > `Connect to KeePassXC` was exhibiting a very weird behavior -- the extension was adding multiple times the same hash, and not re-requesting connection to KPXC.
you should probably take a look at that...
to reproduce the issue from a working situation:
1. stop Thunderbird,
2. clean all associations from KPXC,
3. start Thunderbird,
4. give a name to the association, e.g. thunder1,
5. verify that it works,
6. restart Thunderbird: possibly repeat from 4.

in the logs, I do get some `WARN` messages due to some unreachable code:

https://github.com/kkapsner/keepassxc-mail/blob/e35e6b66a3ad7e7480d018b480be7e43a6a4e829/from-keepassxc-browser/keepass.js#L1171-L1188

**Comment by kkapsner** [comment]
> could you please briefly explain what the two buttons do?

Usually they should not be required to be used. Just to trouble shoot (as they did here).
The `Reconnect to Native Messaging` can be used if the technical connection to the database is lost (it may happen when you close KeePassXC). And the `Connect to KeePassXC` establishes the logical connection - i.e. it does the association.



>  **I should not do that**!

That's not what I intended and I think it worked at some point. It's a very weird issue and I think it's a Thunderbird bug. The association key is simply not stored in the storage.
But I think I can provide a workaround.

> the extension was adding multiple times the same hash

This is just a display bug I have to deal with.

> to reproduce the issue from a working situation:

Thanks. This helped a lot to figure the problem out.

> in the logs, I do get some `WARN` messages due to some unreachable code (try-return here, but probably is unrelated although weird)

It's not weird but kind of intended. I copied the code that deals with the communication with KeePassXC from KeePassXC-Browser. But this code contains some browser specific code that needed to be disabled. I simply put a `return` to disable it - it keeps the files similar enough so I can update the code easily.

**Comment by piramiday** [comment]
> Thanks. This helped a lot to figure the problem out.

did you manage to replicate it, then? happy to help.

> I simply put a return to disable it - it keeps the files similar enough so I can update the code easily.

okay, got it. is there a better way to avoid warnings? maybe commenting the code out? :man_shrugging:

**Comment by kkapsner** [comment]
Yes, I manage to replicate it. It only happens when die association dialog is shown during the startup of Thunderbird. Usually the dialog is shown when you install the extension and then the problem does not happen. But as you had problems with the setup before you had the rare situation that the extension was installed but not associated.

But I managed to create a workaround for this problem and it will be part of the next version (which hopefully will be released soon).
