### ISSUE TITLE
Cannot connect to KeePassXC

### ISSUE THREAD

**Issue by matthieuy** [kkapsner/keepassxc-mail#18]
Hi,

I switch from keepass to keepassXC and I try to connect thunderbird.
My version :
* O.S : Linux Debian 10
* Thunderbird : 68.9.0 (64bits)
* KeepassXC-mail : v0.1.3
* KeepassXC : I have v2.3.4 from deb repot and 2.5.4 from AppImage (I try these two version with same result)

Firefox work fine (I enable the Browser integration) but I can't use it with Thunderbird.
In the "error console", I have this message :
```Failed to connect: Unknown error
Connecting to native messaging host de.kkapsner.keepassxc_mail
Unix error 13 during operation open on file /home/matthieu/.mozilla/native-messaging-hosts/de.kkapsner.keepassxc_mail.json (Permission non accordée)
```
This message display in while every second.

I try a chmod 777 on the file and the directory but same result.
This file content : 
```
{
    "allowed_extensions": [
        "keepassxc-mail@kkapsner.de"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "de.kkapsner.keepassxc_mail",
    "path": "/usr/bin/keepassxc-proxy",
    "type": "stdio"
}
```

When I click on the button "Connect to KeePassXC", I had this error :
```
Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.
Connecting to native messaging host de.kkapsner.keepassxc_mail
```
and the previously error (wrogn right) display again in a while.

What I do wrong ?

**Comment by kkapsner** [comment]
My file has 644 as permission - I think 400 should be sufficient if the owner of the file is the same user that runs Thunderbird.
What are the permissions (owner and mode) on `org.keepassxc.keepassxc_browser.json`?

**Comment by matthieuy** [comment]
The owner is the same as who run thunderbird.
I change the permission to 777

**Comment by kkapsner** [comment]
Please give me the results of a `ls -la /home/matthieu/.mozilla/native-messaging-hosts/`.

**Comment by matthieuy** [comment]
```
total 16
drwxrwxrwx 2 matthieu matthieu 4096 juin  20 14:23 .
drwx------ 6 matthieu matthieu 4096 juin  19 16:53 ..
-rwxrwxrwx 1 matthieu matthieu  251 juin  20 14:41 de.kkapsner.keepassxc_mail.json
-rwxrwxrwx 1 matthieu matthieu  261 juin  20 14:47 org.keepassxc.keepassxc_browser.json
```

**Comment by kkapsner** [comment]
That's weird. Not sure how to debug this...  you could try to use the original keepassxc json file with Thunderbird:
* in `org.keepassxc.keepassxc_browser.json` add `,"keepassxc-mail@kkapsner.de"` to the `allowed_extensions`
* extract the `.xpi` file from KeePassXC-mail (it's a simple zip archive) and change in the `main.js` the line `keepass.nativeHostName = "de.kkapsner.keepassxc_mail";` to `keepass.nativeHostName = "org.keepassxc.keepassxc_browser";` - rezip, rename and install

**Comment by matthieuy** [comment]
Same problem but the message say :
```Unix error 13 during operation open on file /home/matthieu/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json (Permission non accordée)```

**Comment by kkapsner** [comment]
OK - so it's no problem with the file... please check the user Thunderbird is running with: `ps -aux | grep thunderbird` (and also `ps -aux | grep firefox` to compare with Firefox)

**Comment by matthieuy** [comment]
I have only one user, this is the same who running thunderbird, firefox, keepassXC : matthieu

**Comment by kkapsner** [comment]
Hm... I start to run out of ideas why this happens...

How did you install Thunderbird? Have you tried to use the binaries directly from Mozilla (https://www.thunderbird.net/en-US/thunderbird/all/)?

**Comment by kkapsner** [comment]
If you still have the problem and provide me with the information I asked for I can reopen this issue.
