### ISSUE TITLE
Upload to https://addons.thunderbird.net

### ISSUE THREAD

**Issue by kkapsner** [kkapsner/keepassxc-mail#2]
Currently not possible as we use the experiment API to interact with the popups.

Not sure how to get this to work, but at the moment I have no problem with it being unsigned as Thunderbird does not complain.

**Comment by kkapsner** [comment]
Since Thunderbird 78 will remove legacy support for MailExtensions  (https://developer.thunderbird.net/add-ons/tb78) it's not worth implementing a legacy layer. So I have to open a feature request for an API that let's me interact somehow with the password requests.

**Comment by kkapsner** [comment]
Created https://bugzilla.mozilla.org/show_bug.cgi?id=1611700

**Comment by kkapsner** [comment]
@jobisoft as you are so helpful at [spodermenpls/smartquotes](https://github.com/spodermenpls/smartquotes) and already know of the feature request linked above (you changed the summary of it) can you give a comment if and when this API will be implemented?

**Comment by jobisoft** [comment]
If I had to decide that on my own I would allow that, but this will probably be a longer process. We need to prevent password exfiltrations. So we have to come up with a mechanism to allow extensions read-write their own passwords but meaningful limit access to others. The whole point if the PW manager is(!) to access common used passwords. We probably need to find a permission prompt based solution.

**Comment by haarp** [comment]
It would be very much preferable to obtain this addon from the official TB repository. Not that the author isn't trustworty, but the additional vetting addons go through is valuable. Especially for something as sensitive as handling email passwords.

Here's hoping Mozilla is going to implement the API. But I fear it'll be a long while...

**Comment by jobisoft** [comment]
Using an Experiment is not a road block for ATN. The only thing we urge developers is to not use blob Experiments, which means the entire add-on being stuffed into the Experiment. What we push for are single-purposed Experiments, which provide functionality not yet available via WebExtension APIs:

https://thunderbird.topicbox.com/groups/addons/Tb635d04ab79cafe7-M27c609abbcf5a4f5efc0f76f/restricting-usage-of-experiments-in-new-add-ons-webextension-api-have-to-be-used-where-possible-and-experiments-must-not-include-the-main-logic

We even list popular Experiments for re-use on our official developer page:

https://developer.thunderbird.net/add-ons/mailextensions#sharing-experiment-apis

**Comment by kkapsner** [comment]
@jobisoft: thanks for clarifying this. I got an error when I tried 2020 mentioning the experiment. Now it seems to work. (It's just weird that the restrictions on strict_max_version are very tight. Even 92.* won't work - 91.* does though.

I just submitted - it should meet the requirement mentioned above. Is there a smooth way for the users to switch to the version hosted at ATN?

**Comment by jobisoft** [comment]
92 is a Beta and for those the max version is not 92.* but 92.0 (all releases of beta versions are smaller than .0)

**Comment by kkapsner** [comment]
Yes - I just realized that after looking deeper at the version page. I think I will use 100.0 for the time being. A quick test on daily worked.

Is the approval process automated or manually? The queue seems not to change.

**Comment by jobisoft** [comment]
> Is the approval process automated or manually? The queue seems not to change.

If it contains an Experiment, there will be a manual (mostly by me, I try to review within 7 day max). Pure WebExtensions are auto approved and will be selected for reviewed by an algorithm.

**Comment by kkapsner** [comment]
> If it contains an Experiment, there will be a manual review

Makes sense.

> mostly by me, I try to review within 7 days max

Good to know. If you have questions you know where to ask (the code of the experiment is a bit entangled).
And no hurry - we waited more than 2 years. Some days do not make a difference.

Thanks again for the insight.

**Comment by mdonz** [comment]
Good discussion, great outcome as far as I understand. Love to see collaboration between good developers. Thank you both for your work.

**Comment by kkapsner** [comment]
Done https://addons.thunderbird.net/thunderbird/addon/keepassxc-mail/!

Thanks @jobisoft!
