### ISSUE TITLE
Server address not correct if hostname != realhostname

### ISSUE THREAD

**Issue by kkapsner** [kkapsner/keepassxc-mail#24]
If `mail.server.serverX.hostname` is not equal to `mail.server.serverX.realhostname` the real host name should be used to find entries.

Is a problem since Thunderbird 78.

**Comment by Ouack23** [comment]
Hello,
I don't know if this is related to this issue or not, but I had a hard time managing KPXC entries for zaclys.net mail service.

Software versions :
* TB 78.5.0 32 bits
* KPXC 2.6.2
* KPXC-mail 0.1.4

Zaclys use the following addresses : 
* imap.zaclys.net
* smtp.zaclys.net

With the above addresses, KPXC-mail is unable to use the database to enter the correct password (using correct imap:// and smtp:// prefixes in the entry).
I discovered that both of them were actually CNAME of the main mail server that serves both IMAP and SMTP features :

```
;QUESTION
imap.zaclys.net. IN A
;ANSWER
imap.zaclys.net. 3582 IN CNAME mail.zaclys.net.
mail.zaclys.net. 3582 IN A 178.33.93.72
;AUTHORITY
;ADDITIONAL
```
```
;QUESTION
smtp.zaclys.net. IN A
;ANSWER
smtp.zaclys.net. 3599 IN CNAME mail.zaclys.net.
mail.zaclys.net. 3599 IN A 178.33.93.72
;AUTHORITY
;ADDITIONAL
```

When I changed both addresses to respectively imap://mail.zaclys.net and smtp://zaclys.net, it worked.

If this is not related, I can open a separate issue.

**Comment by kkapsner** [comment]
Could be the same issue. #26 should help in the future if something like this happens.

**Comment by kkapsner** [comment]
@Ouack23: please check if the issue is solved with version 0.1.5

**Comment by Ouack23** [comment]
It still doesn't work, but now we know why it's happening !
I get the following message even though my IMAP configuration is set to imap.zaclys.net in TB.
```
got credential request: Object { host: "imap://mail.zaclys.net", login: "31704", loginChangeable: false }
```

**Comment by kkapsner** [comment]
Can you test on TB 78.5.0 with a new profile?

PS: If you want you could translate KPXC-mail to French... translate the `"message"`s in https://github.com/kkapsner/keepassxc-mail/blob/master/_locales/en/messages.json or wait until #28 is ready.

**Comment by Ouack23** [comment]
[TB 78.5.0](https://www.archlinux.org/packages/testing/x86_64/thunderbird/) is currently in testing repository on arch.
I"ll wait for it to be out of testing before installing it. I'll try to make a new profile. Is it possible to just move my profile and put it back to use all my accounts again ?

**Comment by kkapsner** [comment]
You can use the `-p` parameter when starting Thunderbird to start the profile manager. There you can create new profiles and switch between profiles.

**Comment by Ouack23** [comment]
TB finally got out of testing and I was able to test what you asked today.

Here is the result, with a new profile each time, using : 
* TB 78.6.0
* KPXC 2.6.2
* KPXC-mail 0.1.5

Results :
* Archlinux : 
  * Using "imap.zaclys.net" i got a "imap.zaclys.net" console log
  * Using "mail.zaclys.net" i got a "mail.zaclys.net" console log
* Windows : 
  * Using "imap.zaclys.net" i got a "imap.zaclys.net" console log
  * Using "mail.zaclys.net" i got a "mail.zaclys.net" console log

So everything seems OK and the issue is solved for me.

**Comment by johannes-hafner** [comment]
As shown in https://github.com/kkapsner/keepassxc-mail/issues/33, the issue is not yet fixed. If hostname differs from realhostname, keepassxc-mail will still look up hostname.

The issue does also exist for userName and realuserName.

**Comment by kkapsner** [comment]
@Ouack23: Do you still have your broken profile? And if so can you check the last test in #33?

**Comment by Ouack23** [comment]
I don't, but I guess I could re-break it by modifying it ...
Is it still needed or do you consider it fixed due to [this message](https://github.com/kkapsner/keepassxc-mail/issues/33#issuecomment-747108665) ?

**Comment by kkapsner** [comment]
No - it would only have been a cross check.
