### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by kkapsner** [kkapsner/keepassxc-mail#28]
Other languages may be of interest.
- [x] create an account at Crowdin
- [x] add some languages of interest

**Comment by Ouack23** [comment]
I'd be happy to translate KPXC-mail to french !
I'll wait for the crowdin project to be created.

**Comment by kkapsner** [comment]
Crowding project created: https://crowdin.com/project/keepassxc-mail

You should be able to start translating.

**Comment by Ouack23** [comment]
FYI I added french translation
Thanks for all your work

**Comment by kkapsner** [comment]
Thanks

**Comment by kkapsner** [comment]
Added the same languages that keepassxc-browser has.
