### ISSUE TITLE
Auto-submit password dialogs

### ISSUE THREAD

**Issue by Jonny007-MKD** [kkapsner/keepassxc-mail#3]
Thank you very much for developing this addon! I have tried it and it is working quite well, so I would like to have it auto-submit the password dialog after it entered it.

**Comment by kkapsner** [comment]
If there is only one matching password entry and you enabled "auto submit" in the options it should work (it does at my end).

But I also want to enable some sort of "auto pick" if several entries are found. Not quite sure how it will work exactly.

**Comment by Jonny007-MKD** [comment]
auto-submit is exactly what I wanted, thanks :)

Perhaps you may add some explaining text for dumb users like me ^^
