### ISSUE TITLE
Duplicated entries generated in KeePassXC-Mail Passwords group

### ISSUE THREAD

**Issue by joebroesel** [kkapsner/keepassxc-mail#31]
Hello,

I seem to have a problem with duplicate entries in my keepass file that seem to keep piling up in the "KeePassXC-Mail Passwords" group. I have created entries for all mail accounts (imap as main URLs, smtp as additional URL entry) in this group. These get correctly selected.
But then additional key entries appear with exactly the same information (except the additional URL entries), a new one almost every day. Interestingly, for some only smtp entries appear, for others only imap entries. I can't see any difference between the different account entries that would trigger this. It also happens for https entries (for webdav calenders in lightning that I currently have to select manually in the drop-down since the server is the same as for the email accounts and it doesn't seem to be able to select the correct https entry (all others are imap/smtp), so selection by protocol does not seem to work.).

Any idea why new entries get regularly created although the original entry is correct and gets picked up? I only have to confirm the correct selection every startup. If you let me know what else to provide (logs, examples of entries, ...) let me know and I'll send them directly.

Thanks a lot for all the great work. Apart from that minor nuisance, the addon works like a charm!

**Comment by kkapsner** [comment]
I saw this problem as well once. You can disable the credential saving in the settings.

If you have this problem on a regular basis I can provide a version for you to test. I think I can simply add a check if the credentials are already in the database and usable.

**Comment by kkapsner** [comment]
Please try the attached version.

[keepassxc-mail-0.1.5.1.zip](https://github.com/kkapsner/keepassxc-mail/files/5659234/keepassxc-mail-0.1.5.1.zip)

**Comment by joebroesel** [comment]
0.1.5.1 works perfectly. No duplicate entries anymore it seems.

Thanks for the quick fix!
