### ISSUE TITLE
Add privacy notice for auto-update feature

### ISSUE THREAD

**Issue by nicoroeser** [kkapsner/keepassxc-mail#35]
Since #7 has been closed by b4d45fde5bd0205821b661e82c42db8dbacdc16a , the add-on can phone home and check for updates. This happens as configured by the user; users can disable automatic update checks for add-ons.

Still, I’d like to suggest to add a short privacy information regarding the update feature. So that users know what happens on an update check, and what the receiver is going to do with the data.

For me personally, this currently has very low priority, because I pull the source code, look at it and build the add-on myself anyway. I’m just creating this issue for completeness so that it is not forgotten; others for whom it is more important may be more interested in it.

**Comment by kkapsner** [comment]
Good point. Any suggestions for the text? The update server is just a hosted web page with static files.

**Comment by nicoroeser** [comment]
As I assume that the server is not located in your basement :wink:, this may involve a pointer to the hosting facility, and their privacy policy, etc. This is probably ready2host, and maybe also Hetzner? I thought, the document in question might be <https://www.ready2host.de/datenschutz.html>, but they seem to have misconfigured something, as this presents the page about their domain offers.

Umm… anyway. We do not want to present the users a looong document of gobbledegookish legalese, and I can’t give legal advice here. It seems reasonable to configure the server in a way that it does not log anything – or, if you like to log stuff, then tell the users what and for what purpose. As this is located in the EU, the [GDPR](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation) comes to mind.

Sorry that I can’t give much better advice for now. Does this help a bit?

**Comment by kkapsner** [comment]
Yes, it's hosted a ready2host. As said: it's only static content and I do not have any logging in place. There is the usual server logging the hosting has in place (I don't think I can change that) but they have to be GDPR compliant.

I added a privacy note in the readme.
