### ISSUE TITLE
Support filling out the primary password

### ISSUE THREAD

**Issue by nicoroeser** [kkapsner/keepassxc-mail#36]
It would be nice if the add-on would support the primary password (“master password”) in Thunderbird.

Use case: you store your private key used for S/MIME in the internal key store of Thunderbird. This key store is protected by the primary password.

**Comment by nicoroeser** [comment]
Support for the primary password should probably also be included in the [WebExtension API for password managers to provide credentials](https://bugzilla.mozilla.org/show_bug.cgi?id=1611700). What do others think?

**Comment by kkapsner** [comment]
I will have to look at the actual Thunderbird code for the master password so see what I can do there.

**Comment by kocjs** [comment]
The same applies for the Thunderbird PGP integration.

**Comment by kkapsner** [comment]
Please try [keepassxc-mail-0.1.6.1.zip](https://github.com/kkapsner/keepassxc-mail/files/6058132/keepassxc-mail-0.1.6.1.zip)

You will have to add a `masterPassword://MozillaThunderbird` (may change in the real release) entry in your password storage.

**Comment by kkapsner** [comment]
(The entry in the password storage also needs a user name.. this will be changed for sure)

**Comment by nicoroeser** [comment]
> Please try [keepassxc-mail-0.1.6.1.zip](https://github.com/kkapsner/keepassxc-mail/files/6058132/keepassxc-mail-0.1.6.1.zip)

Works like a charm! Many, many thanks, @kkapsner , this is a great feature and a big time saver!

Side note: it seems that you are using the window title for detecting the primary login window. I have the feeling that stuff like this might break with a rebranded package, something like the former Icedove. But I also don’t see a pressing need to work around this right now if there is no such package in wide use.

**Comment by kkapsner** [comment]
I use the title and the displayed text to detect the window. This is done by the string bundle services so changes in translations and rebranding should be covered.

I decided that the final entry URL has to be `masterPassword://Thunderbird` and the user name is optional.

**Comment by kkapsner** [comment]
Version 0.1.7 is released.
