### ISSUE TITLE
When master password is obtained from KeePassXC a new copy is saved in "KeePassXC-Mail-Passwords" group

### ISSUE THREAD

**Issue by jonasc** [kkapsner/keepassxc-mail#39]
Hi,

after updating to 0.1.7 it was a nice surprise that the master password is also available via KeePassXC. However, after entering it manually or after selecting one from the database a new copy is saved into the database:

![screenshot](https://user-images.githubusercontent.com/2046766/110612436-7ac5f700-8190-11eb-85e6-62c9b861cae3.jpg)

This is new behavior as the group "KeePassXC-Mail-Passwords" was newly created by the extension. The other entries (for IMAP, etc.) work as before.

Edit: Just to be more precise, the picture above is after I restarted Thunderbird three times in a short interval, as indicated by the times.

**Comment by jonasc** [comment]
I dug a little further and disabling the option _Save new credentials_ in the extension settings stops this from happening. I'm still not sure why it kept adding the entry as new and didn't do any of that for the IMAP passwords.

**Comment by kkapsner** [comment]
> I'm still not sure why it kept adding the entry as new and didn't do any of that for the IMAP passwords.

It*s because there is a bug in the code... ;)

**Comment by kkapsner** [comment]
Version 0.1.7.1 is out.
