### ISSUE TITLE
Add info about requirements at KeePass entries

### ISSUE THREAD

**Issue by Jonny007-MKD** [kkapsner/keepassxc-mail#4]
Installing the add-on was quite easy, but at firsrt it did not find any entries. So I had to open the debugger and see what it is looking for. Turns out you are passing the protocol and the host name as URL, i.e. `imap://host.name`. This is something, that should be documented in the README.md.

Additionally: Now I have modified all my URLs to match the imap request, but for sending it has to match with smtp. How can I achieve that without duplicating the entry?

Thanks!

**Comment by kkapsner** [comment]
I added a note in the README.md regarding the schemas and (not) duplicating entries.

In the "Browser Integration" section of an entry in KeePassXC you can specify additional URLs for it. I added the `smtp` server there.

**Comment by Jonny007-MKD** [comment]
Thanks :+1:

**Comment by Jonny007-MKD** [comment]
These settings are not available in my old KeePassXC 2.3.4 debian version. I have to compile it on my own.

**Comment by kkapsner** [comment]
Oh... they are available in 2.5.1 - no idea when they were introduced.

Another way is to use references in the second keepassxc entry so you do not have to change the password twice if you have to.

**Comment by kkapsner** [comment]
Maybe https://keepassxc.org/docs/#faq-appsnap-support is an option.

**Comment by Jonny007-MKD** [comment]
I'm running LMDE (a Debian) and have no snap, yet. Compiling it myself really was no problem using [the guide](https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC). I only had to iterate over the "missing library XXX" messages and install it using apt, and now I have a recent version. That's a good feeling :)
