### ISSUE TITLE
Issue with masterPassword detection

### ISSUE THREAD

**Issue by sam9032** [kkapsner/keepassxc-mail#45]
Hey there,
first of all, thank you for the addon! Without the features I wouldn't migrated to Keepass XC.

I can't get the thunderbird master password to fill in with the Keepass XC entry.
I have added the masterPassword://Thunderbird entry both in the url column and under browser integration --> additional urls, but when I start Thunderbird and the materpassword field pops up, nothing happens.

Did I miss something?

**Comment by mdonz** [comment]
I don't know the answer to your question but just as an idea for an alternative solution - do you really need a Thunderbird master password still? With the combination of KeepassXC and keepassxc-mail as an add-on, I have all my Thunderbird passwords stored in KeepassXC hence do not need a Thunderbird master password at all.

**Comment by sam9032** [comment]
I do the same with the normal mail passwords. But for example the tb sync addon has no support for the KeepassXC addon and saves the stored accounts automatically in the thunderbird password store.
Oauth also often causes problems, that works more reliably for me when I have it in the thunderbird password store.

**Comment by kkapsner** [comment]
I noticed that on startup the prompt for the master password get opened before KeePassXC-Mail gets loaded. I will have to dig a little bit deeper to figure out if I can solve this issue.
What happens if you cancel the very first prompt?

**Comment by sam9032** [comment]
Thank you! If I cancel the first request, everything works fine.

**Comment by kkapsner** [comment]
OK - that's good to hear. I don't think there is anything I can do about this problem. The loading of the mail-extension would have to be earlier in the startup process and this is baked in the Thunderbird code.
