### ISSUE TITLE
No logins found

### ISSUE THREAD

**Issue by phHartl** [kkapsner/keepassxc-mail#46]
Similar to #12 I had problems getting logins from database despite my entries being configured the right way. After debugging the extension myself with the debugging tools of Thunderbird, I also found out it was the mysterious `Error 8: KeePassXC association failed, try again`. After some searching, I found this issue on the main KeePassXC repository (https://github.com/keepassxreboot/keepassxc/issues/1559). This error appears when the association window doesn't pop up correctly. In my case, it appeared too early when installing/enabling the extension. After approving the request, the add-on still didn't work. I proceeded to disable the add-on, deleted the approved connection inside KeePassXC via Database Settings → Browser Integration. And re-enable the add-on, which then worked as expected by connecting it again. 
I'm just leaving this here in case somebody got the same problem in the future. Feel free to immediately close this issue.

Thanks for developing this extension & best regards

**Comment by kkapsner** [comment]
Thanks for sharing your experience. I hope others with the same problem find this.
