### ISSUE TITLE
Not working with KeePassXC 2.6.6 on ubuntu

### ISSUE THREAD

**Issue by kevinkk525** [kkapsner/keepassxc-mail#48]
I'm on ubuntu 20.04 and the default version of keepassxc in the ubuntu repository is 2.4.3 which works out of the box with thunderbird and the keepassxc-mail plugin. 
If I however add a repository from the keepassxc homepage to update to version 2.6.6, the plugin stops working and I can't get it working, even with a new thunderbird installation. It just doesn't create a connection to keepassxc. 
Downgrading keepassxc again makes it work again.

**Comment by mdonz** [comment]
I seem to be running exactly that combination for a long time without any such issue (Ubuntu 20.04 LTS, KeePassXC 2.6.6 from repository http://ppa.launchpad.net/phoerious/keepassxc/ubuntu, keepassxc-mail plugin 0.1.8 and Thunderbird currently 78.13.0, 64bit).
It has been quite a long time since installation and I cannot remember any details but happy to try to help.

**Comment by kevinkk525** [comment]
Strange, that's how I installed it but it's not working unless I use the old KeePassXC version.
I can switch between both versions and will immediately see the difference (reconnecting Thunderbird every time or starting with an unconfigured plugin).

Only thing I could add about my setup is that I run my Ubuntu 20.04 as an LXD installation with KDE Plasma but that shouldn't be the problem.

**Comment by kevinkk525** [comment]
One thing that I could add but seems unlikely to be related: When I use KeePass2 + keepassnatmsg plugin, Thunderbird creates the connection to KeePass2 correctly but after that every password request just gets "stuck" and never receives the password, the prompt will just stay open.
I don't think this is really related because it seems like a different problem but just thought I'd mention it.

**Comment by mdonz** [comment]
I do not use the "keepassnatmsg" plugin at all. Sorry, do not understand why this is needed at all for Thunderbird where the keepassxc-mail plugin seems to do everything that I expect from the integration (and "KeePassXC-Browser" as plugin for Firefox)

**Comment by kevinkk525** [comment]
It is not needed with keepassxc-mail and KeePassXC. It is only needed as a plugin for KeePass2 in KeePass. I was just making a comparison of completely different environments.

**Comment by kkapsner** [comment]
Do you see any related entries in the developer console (Ctrl + Shift + J)?

PS: KeePassXC 2.6.6 is working fine for me on Linux.

**Comment by kevinkk525** [comment]
it's like the KeePassXC server just isn't running at all. The console throws the same errors while KeePassXC is closed as well as while it is open:

```
Connecting to native messaging host de.kkapsner.keepassxc_mail keepass.js:1059:13
Failed to connect: Unknown error keepass.js:1029:13
```

As soon as I downgrade KeePassXC again and open it, the console immediately shows a successful connect..

**Comment by kkapsner** [comment]
@kevinkk525 : Did you rerun the [shell command](https://github.com/kkapsner/keepassxc-mail#linux) to adjust the Native Messaging configuration?

**Comment by kkapsner** [comment]
Any updates?

**Comment by kevinkk525** [comment]
Sorry not feeling well enough lately. I'll try again once I get better. But thanks for the ping.

**Comment by nicoroeser** [comment]
I suppose that it is timing-related. When Thunderbird starts up, it seems to take some time until the passwords can be read from KeePassXC.

I was used to select „Cancel“ in the first dialog, which asks for the main password, that opened before the Thunderbird main window appeared. This closed the dialog, and a second later it opened again; this time, keepassxc-mail had obviously been able to fill in the password.

This behavior is no longer true: now, when I start Thunderbird, I have to cancel quite a lot of dialogs (asking for main password, or individual IMAP passwords), and also switch to another IMAP folder to force a reconnection (including new password prompt). Then it works again.

So far, I haven’t looked more deeply into this issue, but perhaps this description helps others.

**Comment by kevinkk525** [comment]
Sorry, might never be able to get back to it.. But who knows..

**Comment by kkapsner** [comment]
OK - no problem.
If you have time to get back to it and still have the problem after rerunning the native messaging setup just post it here and I will reopen this issue.
