### ISSUE TITLE
Thunderbird cannot find NativeMessagingHosts app (macOS 10.15.2)

### ISSUE THREAD

**Issue by alexandrospanagiotidis** [kkapsner/keepassxc-mail#5]
Hi!

Thank you for creating this addon! I followed the README but I could not connect to KeePassXC from Thunderbird on macOS Catalina (10.15.2).
I dug around in the developer console and found that Thunderbird (68.4.1 (64-bit)) does not use _~/Library/Application Support/Mozilla/NativeMessagingHosts/_ (which was already there due to browser integration in KeePassXC) but _~/Library/Mozilla/NativeMessagingHosts_ instead, so I created a symlink:

```
cd ~/Library/Mozilla
ln -s ../Application\ Support/Mozilla/NativeMessagingHosts/
```

I think I didn't need to restart Thunderbird; it just started working then.

Maybe you would like to update the documentation :)

All the best,
Alex

**Comment by kkapsner** [comment]
Thanks for your feedback. The MacOS instructions were completely untested as I have no Mac - they were based on the Mozilla documentation of it.

I will update the README accordingly.

**Comment by kkapsner** [comment]
Can you please verify that they are correct now?

**Comment by alexandrospanagiotidis** [comment]
I deleted my symlink and ran the `ln` command from the README and it still works.
So I guess it is correct now :)

**Comment by kkapsner** [comment]
Great.
