### ISSUE TITLE
compability for thunderbird 91.4.1

### ISSUE THREAD

**Issue by Skizzie** [kkapsner/keepassxc-mail#51]
The addon do not work anymore due to new version of Thunderbird. 

Are you planning on updating the addon for the newest version if possible?

**Comment by kkapsner** [comment]
It is working for me with 91.4.1

What exactly is not working? Any messages in the error console (Ctrl + Shift + J)? What OS are you on? Which language are you using?

PS: Sometimes the extension is not completely loaded when the first login prompts are opened. Unfortunately there is nothing I can do about that. Simply dismiss the prompts and when they open later it usually works.

**Comment by Skizzie** [comment]
I only used to use the addon for autofilling my master password when i opened up my Thunderbird, and it stopped working with the 91 version for me.

I'm using Windows 10 21H1

The Thunderbird language is set to English.

I had some [errors ](https://imgur.com/a/AKXAsNq)showed up, but i'm not really sure if it has anything to do with the addon or not.

**Comment by kkapsner** [comment]
Unfortunately there is nothing I can do about that problem. See #45 for further information. The only "solution" I can offer is to cancel the first prompt. In the tests I did back then it worked in the second prompt.

The errors are not from the KPM.
