### ISSUE TITLE
Thunderbird 91.5.0 Master Password not retrieved

### ISSUE THREAD

**Issue by ecoutinho** [kkapsner/keepassxc-mail#53]
On Thunderbird 91.5.0 and Keepassxc-mail 0.1.9.1 the master password is not retrieved from KeepassXC, even when I cancel the password prompt several times as mentioned on a previous issue. On the Toolbox Extension Console, it shows "got credential request" for my accounts, but there isn't any request for "masterPassword://Thunderbird". It seems it is not detecting the password prompt.

**Comment by kkapsner** [comment]
You are right. They (again) changed the name of a translation-able string...

Please try if this works for you: [keepassxc-mail-0.1.9.2.zip](https://github.com/kkapsner/keepassxc-mail/files/7850231/keepassxc-mail-0.1.9.2.zip)

**Comment by ecoutinho** [comment]
It's working, thanks!

I had to Cancel the first prompt, then it said "No passwords found", then pressed Retry and it "Picked entry Thunderbird" and authenticated successfully.
