### ISSUE TITLE
Support the "ldap://" scheme

### ISSUE THREAD

**Issue by fpoirotte** [kkapsner/keepassxc-mail#54]
First and foremost, thank you for your work on this extension!
It's great to finally have a proper KeePassXC integration for Thunderbird.

Would it be possible to add support for the "ldap//" scheme?
It is used by Thunderbird to look up email addresses from an LDAP directory (see https://wiki.mozilla.org/Thunderbird:Help_Documentation:Connecting_to_an_LDAP_address_book for more information).

Best regards, François

**Comment by fpoirotte** [comment]
To make things clear: when attempting to auto-complete an email address using an LDAP directory, it keeps saying that no password was found and prompting for the password, although it was previously saved into KeePassXC by the extension.

Manually copying the password from KeePassXC into the prompt does bring up suggestions, meaning the stored password is indeed correct.

**Comment by kkapsner** [comment]
LDAP is supported. The problem is that entries without a username get filtered, which is wrong in that case.

Can you please test this:
[keepassxc-mail-0.1.10.1.zip](https://github.com/kkapsner/keepassxc-mail/files/7928856/keepassxc-mail-0.1.10.1.zip)

**Comment by fpoirotte** [comment]
Hello, I just tested the attached version and can confirmed that it fixed the issue for me.
Thanks again!
