### ISSUE TITLE
Lightning Calendar password request not working anymore

### ISSUE THREAD

**Issue by joebroesel** [kkapsner/keepassxc-mail#55]
Hi,

with the last update of thunderbird (91.5.0 (64-bit) and keepassxc-mail (0.1.11), password requests for CalDav Calenders in Lightning do not seem to work anymore. Worked like a charm before (I always got a dropdown with search hits), but now it can't find any passwords anymore (it works for the IMAP accounts without problem).

Not sure how I have to enter the entry in KeepassXC to find it again. Here is the request information from the Developer Console:

got credential request: 
Object { host: "https://sven-magg.de/nextcloud/remote.php/dav/calendars/xxxxx/xxxxx/", login: "", loginChangeable: false }
host: "https://sven-magg.de/nextcloud/remote.php/dav/calendars/xxxxx/xxxxx/"
login: ""
loginChangeable: false

The windows says: "https://sven-magg.de is requesting your username and password. The site says: “Nextcloud" "

Is there a way to edit the entry in KeePassXC so that the password request works again? The URL in the entry is currently set to  "https://sven-magg.de/nextcloud/" 

Thanks for the help! And great work on the addon! :)

**Comment by kkapsner** [comment]
I already noticed the problem myself and am working on a fix. Shouldn't be too difficult.

**Comment by kkapsner** [comment]
Version 0.1.12 solves the problem for me.

**Comment by joebroesel** [comment]
Yes, does for me as well. Even better than before even, since it now identifies the exact entry and does not give all the users connected to the domain (i.e. automatically closes the form since only one entry was found). Was that a change in the new version, or did I unknowingly change something in the KeePass entry that made it possible to better identify the exact entry?

Thanks for the fast response! Awesome work!

**Comment by kkapsner** [comment]
Should be a change in the new version(s).

> Thanks for the fast response! Awesome work!

You're welcome.
