### ISSUE TITLE
Migrate to extension version 1.8.0

### ISSUE THREAD

**Issue by varjolintu** [kkapsner/keepassxc-mail#58]
Just a heads up because I noticed the project is using `background/keepass.js` script. In the upcoming extension version that script is divided to `keepass.js` and `client.js`. Of course you are free to use the older version, but at some point I think it's recommended to use updated scripts.

**Comment by kkapsner** [comment]
Thanks for the heads up. I updated keepass.js irregularly to avoid incompatibilities and plan to do so in the future.
Is there already a schedule when the next extension version will be released?

**Comment by kkapsner** [comment]
Version 1.8.0 is out - so time for me to do some ground work.

**Comment by kkapsner** [comment]
Need to increase the strict_min_version to be able to support these (`??`-operator is used). Will go up to 74 so I can also use `?.`.
