### ISSUE TITLE
Support for "Skip auto-submit for this entry"

### ISSUE THREAD

**Issue by pauleve** [kkapsner/keepassxc-mail#6]
In the "Browser Integration" settings of an entry, keepassxc gives the ability to check "Skip auto-submit for this entry" (which creates a property BrowserSkipAutoSubmit=true).
I would expect that this should override the global "auto submit" setting of the thunderbird extension, but it doesn't.

**Comment by kkapsner** [comment]
Good point. Will incorporate that.

**Comment by kkapsner** [comment]
Please try https://github.com/kkapsner/keepassxc-mail/releases/tag/v0.1.1

**Comment by pauleve** [comment]
Seems to work as expected, thanks!
