### ISSUE TITLE
Unable to connect to native messaging

### ISSUE THREAD

**Issue by Jonny007-MKD** [kkapsner/keepassxc-mail#61]
Hi,

I was using this extension from the very beginning :+1: thanks for your work! In the meantime I switched to the official version and it kept working.

Yesterday I upgraded from LMDE 4 to LMDE 5 (now Debian Bullseye) and I cannot make it work anymore.
I have run the command to create the json file in ~/.mozilla/native-messaging-hosts.

Looking into the debug console of Thunderbird I see some errors related to native messaging:

    ExtensionError: No such native application org.keepassxc.keepassxc_browser [ExtensionUtils.jsm:58:5](resource://gre/modules/ExtensionUtils.jsm)
    this.ports.get(...) is undefined [ExtensionParent.jsm:366](resource://gre/modules/ExtensionParent.jsm)
    
    Failed to connect: Unknown error [keepass.js:1074:13](moz-extension://aac4f9b4-609c-4568-92e0-2225eb6b1c18/from-keepassxc-browser/keepass.js)
    Try native application org.keepassxc.keepassxc_mail [main.js:24:11](moz-extension://aac4f9b4-609c-4568-92e0-2225eb6b1c18/main.js)
    Connecting to native messaging host org.keepassxc.keepassxc_mail [keepass.js:1104:13](moz-extension://aac4f9b4-609c-4568-92e0-2225eb6b1c18/from-keepassxc-browser/keepass.js)
    ExtensionError: No such native application org.keepassxc.keepassxc_mail [ExtensionUtils.jsm:58:5](resource://gre/modules/ExtensionUtils.jsm)

Any ideas?

**Comment by kkapsner** [comment]
Works in my VM. Did you enable the browser integration for Firefox in KeepassXC?
What is the content of ~/.mozilla/native-messaging-hosts/de.kkapsner.keepassxc_mail.json?

**Comment by Jonny007-MKD** [comment]
Yes, it does work in Firefox.

    $ cat ~/.mozilla/native-messaging-hosts/de.kkapsner.keepassxc_mail.json
    {
        "allowed_extensions": [
            "keepassxc-mail@kkapsner.de"
        ],
        "description": "KeePassXC integration with native messaging support",
        "name": "de.kkapsner.keepassxc_mail",
        "path": "/usr/local/bin/keepassxc-proxy",
        "type": "stdio"
    }
    
    $ cat ~/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json 
    {
        "allowed_extensions": [
            "keepassxc-browser@keepassxc.org"
        ],
        "description": "KeePassXC integration with native messaging support",
        "name": "org.keepassxc.keepassxc_browser",
        "path": "/usr/local/bin/keepassxc-proxy",
        "type": "stdio"
    }


The path to keepassxc-proxy is correct.

**Comment by kkapsner** [comment]
Hm... which version/type of Thunderbird are you using?

**Comment by Jonny007-MKD** [comment]
I'm using Firefox 100.0.2 and Thunderbird 91.9.0.

I created a new profile and did not set up anything except installing keepassxc-mail. This is the log output:

    WebExtensions: KeePassXC-Mail: unable to get smtpEnterPasswordPromptTitle from bundle compose 2 [implementation.js:34](jar:file:///tmp/asdf/extensions/keepassxc-mail@kkapsner.de.xpi!/experiment/implementation.js)
    WebExtensions: KeePassXC-Mail: unable to get imapEnterPasswordPromptTitle from bundle imap [implementation.js:34](jar:file:///tmp/asdf/extensions/keepassxc-mail@kkapsner.de.xpi!/experiment/implementation.js)
    WebExtensions: KeePassXC-Mail: unable to get pop3EnterPasswordPromptTitle from bundle local 2 [implementation.js:34](jar:file:///tmp/asdf/extensions/keepassxc-mail@kkapsner.de.xpi!/experiment/implementation.js)
    WebExtensions: KeePassXC-Mail: unable to get loginDialog.label from bundle wcap 2 [implementation.js:34](jar:file:///tmp/asdf/extensions/keepassxc-mail@kkapsner.de.xpi!/experiment/implementation.js)
    WebExtensions: KeePassXC-Mail: unable to get PromptUsernameAndPassword2 from bundle commonDialog 2 [implementation.js:34](jar:file:///tmp/asdf/extensions/keepassxc-mail@kkapsner.de.xpi!/experiment/implementation.js)
    WebExtensions: KeePassXC-Mail: unable to get PromptPassword2 from bundle commonDialog [implementation.js:34](jar:file:///tmp/asdf/extensions/keepassxc-mail@kkapsner.de.xpi!/experiment/implementation.js)
    WebExtensions: KeePassXC-Mail: unable to get CertPassPromptDefault from bundle pipnss [implementation.js:34](jar:file:///tmp/asdf/extensions/keepassxc-mail@kkapsner.de.xpi!/experiment/implementation.js)
    WebExtensions: KeePassXC-Mail: unable to register support for CardBook 
    Exception { name: "NS_ERROR_FILE_NOT_FOUND", message: "", result: 2152857618, filename: "jar:file:///tmp/asdf/extensions/keepassxc-mail@kkapsner.de.xpi!/experiment/implementation.js", lineNumber: 742, columnNumber: 0, data: null, stack: "@jar:file:///tmp/asdf/extensions/keepassxc-mail@kkapsner.de.xpi!/experiment
    implementation.js:742:45\nasyncLoadModule/module.asyncLoaded<@resource://gre/modules/ExtensionCommon.jsm:1677:14\n", location: XPCWrappedNative_NoHelper }
    [implemfentation.js:788](jar:file:///tmp/asdf/extensions/keepassxc-mail@kkapsner.de.xpi!/experiment/implementation.js)
    No chrome package registered for chrome://cardbook/content/cardbookRepository.js
    ExtensionError: No such native application de.kkapsner.keepassxc_mail [ExtensionUtils.jsm:58:5](resource://gre/modules/ExtensionUtils.jsm)
    this.ports.get(...) is undefined [ExtensionParent.jsm:366](resource://gre/modules/ExtensionParent.jsm)
    ExtensionError: No such native application org.keepassxc.keepassxc_mail [ExtensionUtils.jsm:58:5](resource://gre/modules/ExtensionUtils.jsm)
    this.ports.get(...) is undefined [ExtensionParent.jsm:366](resource://gre/modules/ExtensionParent.jsm)
    ExtensionError: No such native application org.keepassxc.keepassxc_browser [ExtensionUtils.jsm:58:5](resource://gre/modules/ExtensionUtils.jsm)
    this.ports.get(...) is undefined [ExtensionParent.jsm:366](resource://gre/modules/ExtensionParent.jsm)

**Comment by Jonny007-MKD** [comment]
I found the reason: I'm using firejail (and forgot about it) and apperantely something changed after the upgrade. If I disable it for Thunderbird, native messaging works just fine :+1:

Sorry for the trouble and thank you very much for the support (and the existence of this addon ;) )

**Comment by kkapsner** [comment]
Makes sense that firejail interferes with the native messaging.

> Sorry for the trouble

No problem.

> thank you very much for the support (and the existence of this addon ;) )

You're welcome.

**Comment by Jonny007-MKD** [comment]
For anybody finding this issue and searching for a better solution than disabling firejail for thunderbird:
This is my thunderbird.local:

    private-bin thunderbird # wtf?
    
    whitelist /media/joni/Data/Sonstiges/Thunderbird # the profile
    ignore disable-mnt
    
    machine-id # we don't need audio or whatever
    
    private-bin date, tr, sed, bash # for some startup script
    
    # KeePassXC Mail
    private-bin keepassxc-proxy
    whitelist ${HOME}/.mozilla
    read-only ${HOME}/.mozilla
