### ISSUE TITLE
bad handling of multiple email accounts for the same provider

### ISSUE THREAD

**Issue by eseb63** [kkapsner/keepassxc-mail#64]
hello,
i discovered your extension when looking for an alternative to  the keebird one for Thunderbird (which is not compatible with post 68 versions), so using KeePass 2.

i made some tests and followed the github readme (maybe might you simplify it now - see my final remark).

my test configuration:
- windows 7 x64
- Thunderbird 91.9 portable with keepassxc-mail 1.0.1
- Keepass 2.51 portable with KeepassNatMsg 2.0.14 plugin
- KeepassXC 2.6.6 portable (no longer needed)
- the portable programs are run from the Liberkey platform.

i created an email account in Thunderbird for my Orange provider (i am french).
i have 2 email addresses for Orange : i configured the second one in Thunderbird (Orange gives access to all addresses with one global password)

when i retrieve emails, the KeepassNatMsg dialog pops up and shows the 2 addresses ; i allow and the correct one is selected (i disabled the autofill option so i can see which one is selected)
BUT 
the retrieved emails are those of the first orange address and not those of the second that is configured in Thunderbird.

i created another email account for the Microsoft provider (outlook.com) : i also have several addresses (Microsoft live accounts), but this time each one requires his own password.
the same behavior occurs : all addresses are shown by the KeepassNatMsg dialog, i allow but  the connection fails because (i assume) the login/password for the wrong address is sent.

i checked the "return only best matching entries for an URL instead of all enries for the whole domain" in the KeepassNatMsg but the problem remains.

i saw that keepassXC-mail was based on keebird : i don't have this problem with keebird : it retrieves each time one entry only.

am i misssing something or is it a bug ? and if so, is it a KeePassXC-mail bug or a KeePassNatMsg one ?

remarks:
1) another small issue : the credential request is case sensitive for the login and host: myaccount@orange.fr works, myaccount@orange.Fr not (the F was capitalized automatically when entering the login) : it wound be more robust if case insentitive ?

2) installation : your readme might be simplified now as KeePassNatMsg supports your extension since the 2.0.11 version (https://github.com/smorks/keepassnatmsg/releases?page=1 and https://github.com/smorks/keepassnatmsg/issues/49)

so

- the point 1 is not necessary for KeePass 2 users
- the powershell script is no longer needed :

KeePassNatMsg detects that no host is installed, asks to install the ones you want,  just check Thunderbird and it creates the registry entries and jason file automatically.
(i spent a lot of time following the readme on my old Windows 7  (Powershell version was oudated and didn't recognize some commands, so upgrade, rights problems etc...) ; i looked further and found that KeePassNatMsg could do the job for me, but it was too late :) )

thanks in advance for your response,
eseb

**Comment by eseb63** [comment]
hello,
i have good news : KeepassXC-mail is for nothing in my 2 issues.

**orange issue :** i had quickly created the second address for testing, but the presentation made by orange is a bit confusing : what they call "add a new email address" is actually adding an alias for the main address. So, it was normal to receive the address1 mails when checking address2. the opposite didn't work due to an orange webmail bug. With a true new address (with its own password), it's working well.

**hotmail issue :** i had used an old test account, but the pop access was disable on the server side (and the error message was confusing).

so, KeepassXC-mail (with KeepassNatMsg) seems to work well for keepass 2 users, even in a portable configuration. 

The only somewhat confusing thing for a Keebird user is that the KeepassNatMsg dialog popup list all adresses of the mail server when checking one of them, but we can disable it for the next times.

i apologize for having posted this issue for bad reasons, and for my incorrect remark about the readme simplification : it could be presently possible for keepass 2 users only (i thought KeepassXC used also the KeepassNatMsg plugin).

as you posted on Keebird page that KeepassXC-mail could be a workaround for keepass 2  users , maybe might you write a dedicated readme section for them, with the simplified process? i think many of them would be interested.

eseb

**Comment by kkapsner** [comment]
>     1. another small issue : the credential request is case sensitive for the login and host: [myaccount@orange.fr](mailto:myaccount@orange.fr) works, [myaccount@orange.Fr](mailto:myaccount@orange.Fr) not (the F was capitalized automatically when entering the login) : it wound be more robust if case insentitive ?

Good point. I will make it case insensitive on the KPM side - I have no idea what KeePassNatMsg does.

>     2. installation : your readme might be simplified now as KeePassNatMsg supports your extension since the 2.0.11 version (https://github.com/smorks/keepassnatmsg/releases?page=1 and [Add support for the keepassxc-mail add-on in Thunderbird smorks/keepassnatmsg#49](https://github.com/smorks/keepassnatmsg/issues/49))

The installation guide was written with KeePassXC in mind. KeePassNatMsg happened to work with it. I will add a section for it.


> hello, i have good news : KeepassXC-mail is for nothing in my 2 issues.

Great and thanks for digging deeper.

> so, KeepassXC-mail (with KeepassNatMsg) seems to work well for keepass 2 users, even in a portable configuration.

Good to hear. I never tested that configuration myself.

> The only somewhat confusing thing for a Keebird user is that the KeepassNatMsg dialog popup list all adresses of the mail server when checking one of them, but we can disable it for the next times.

That's a limitation of the native messaging. I cannot provide a login (email address) to KeePass for it to filter. The filtering is done later when I retrieved the credentials. So I cannot change that unfortunately.

> i apologize for having posted this issue for bad reasons, and for my incorrect remark about the readme simplification : it could be presently possible for keepass 2 users only (i thought KeepassXC used also the KeepassNatMsg plugin).

No problem. I appreciate your input and remarks. Only with feedback from other users open source projects like this can get better.

> as you posted on Keebird page that KeepassXC-mail could be a workaround for keepass 2 users , maybe might you write a dedicated readme section for them, with the simplified process? i think many of them would be interested.

Sure will do (see above).
