### ISSUE TITLE
Does not find or cannot connect to databae

### ISSUE THREAD

**Issue by FranzAtGithub** [kkapsner/keepassxc-mail#66]
Hi,

I resently switched to Fedora + Wayland and the keepass autotype feature does not work there apparently.
For my Firefox  I installed KeepassXC-Browser and it works nicely. I was very happy to see this Thunderbrid-Add-On that from what I understand seems to be the equivalent.

I installed the Add-On (currently running 1.0.2.1).
When I start Thunderbird the password dialog show "Loading passwords..." but after roughly 2 minutes is switches to "No passwords found". KeepassXC is opend and unlocked.

What can I do? :)
How can I provide more debugging information?

Would really love to get this working.

Ty a lot for the work here.
Franz

OS: Fedora 36
Thunderbrid version: 91.10.0
Keepasscs-mail version:  1.0.2.1

**Comment by kkapsner** [comment]
In the addon overview page of Thunderbird is a gear wheel in the top left. There is an option to debug add-ons. Then you can inspect the add-on and then you will see the console of the add-on:
![grafik](https://user-images.githubusercontent.com/1105157/176036995-839637d1-20ea-4c7b-a935-fb963438766b.png)

There you might see the problem.

**Comment by FranzAtGithub** [comment]
Sadly this does not give too much information.
I see these lines repeating:

![Screenshot from 2022-06-27 23-27-36](https://user-images.githubusercontent.com/62662135/176038620-d299513d-cbb4-4b2a-bd76-cc235f5b6387.png)

**Comment by kkapsner** [comment]
Hm... the name of the native application should not be the same all the time. Does it cycle between "de.kkapsner.keepassxc_mail", "org.keepassxc.keepassxc_mail", and "org.keepassxc.keepassxc_browser"?

Did you follow these instructions: https://github.com/kkapsner/keepassxc-mail#installation-for-keepassxc

**Comment by FranzAtGithub** [comment]
I am pretty sure I followed the installation instructions exactly.

But you are right the applications changes. I originally posted only parts of what I see in the log because I didn't want to leak personal information. But I hope I actually removed it now :)

Here is the full log.
![Screenshot from 2022-06-28 19-08-58](https://user-images.githubusercontent.com/62662135/176242408-3ccc9ea7-9a39-4974-b20a-1929d77f2dff.png)

**Comment by kkapsner** [comment]
Seems similar to  #61. Do have some hardening software/configuration?
What is the content of  ~/.mozilla/native-messaging-hosts/de.kkapsner.keepassxc_mail.json and  ~/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json?

**Comment by FranzAtGithub** [comment]
I think the json files are correct:

![image](https://user-images.githubusercontent.com/62662135/176382834-3b752350-012d-48fe-835f-3cff759e1036.png)

I do not have firejail installed. Here is a screenshot of the console filtered for errors:

![image](https://user-images.githubusercontent.com/62662135/176386410-e54062e1-c67b-4237-8327-16761813587b.png)

Sadly I am completely lost in trying to understand this ...

**Comment by kkapsner** [comment]
I'm not able to reproduce your problem in a Fedora VM.
How did you install Thunderbird? (I installed it via dnf)
If it works in Firefox then there is some security software/feature in place (maybe SELinux... but only you know your system). Otherwise you should get entries in you console stating "This extension does not have permission to use native manifest ~/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json"

**Comment by kkapsner** [comment]
Good to hear that it works now.

> I installed via a flatpack 

Interesting that it does not work with flatpack.

> But this seems to be the problem.Stupid me ...

No problem. I also did not know that it does not work in flatpack on Fedora.

> Ty a lot.

You're welcome.
