### ISSUE TITLE
Do not create popups for passwords when `Auto submit` is selected

### ISSUE THREAD

**Issue by txtsd** [kkapsner/keepassxc-mail#68]
I have `Auto submit` selected in Preferences.

I expect this to work in the background without creating a popup to sign in to every account.

EDIT: Excellent extension btw. Just what I needed.

**Comment by kkapsner** [comment]
I really like the idea - these flashing popups are annoying.

But I'm not sure if it's possible... let's see.

**Comment by kkapsner** [comment]
Since I cannot directly control if these popups are opened I tried some indirect methods. I think under certain circumstances I can prevent the popups.

**Comment by kkapsner** [comment]
I managed to start my Thunderbird with only one password popup. I think that's the best I can do as it opens before the webExtension is loaded. So no chance of preventing that.

Please try [keepassxc-mail-1.1.1.zip](https://github.com/kkapsner/keepassxc-mail/files/9579282/keepassxc-mail-1.1.1.zip)

**Comment by txtsd** [comment]
Good progress on this! Although it still isn't ideal. If Firefox is able to not throw popups at us, Thunderbird should be able to avoid it too. I also find my Thunderbird crashes a few times per day when I use this extension.

**Comment by kkapsner** [comment]
Firefox has an API for webExtensions to react to these password popups. Thunderbird does not: https://bugzilla.mozilla.org/show_bug.cgi?id=1611700

But with a different profile I was able to start Thunderbird without any popup - so it might depend on the profile.

> I also find my Thunderbird crashes a few times per day when I use this extension.

I do not have this problem. Please open a separate issue for this problem if you have more detailed information.

**Comment by txtsd** [comment]
> Firefox has an API for webExtensions to react to these password popups. Thunderbird does not: [bugzilla.mozilla.org/show_bug.cgi?id=1611700](https://bugzilla.mozilla.org/show_bug.cgi?id=1611700)

Thanks for the information. I bumped that issue.

**Comment by kkapsner** [comment]
Latest development version: [keepassxc-mail-1.1.1.zip](https://github.com/kkapsner/keepassxc-mail/files/9592769/keepassxc-mail-1.1.1.zip)

**Comment by kkapsner** [comment]
I managed to get rid of the last popup (it was a bug and not due to the loading order...)

[keepassxc-mail-1.1.1.zip](https://github.com/kkapsner/keepassxc-mail/files/9602807/keepassxc-mail-1.1.1.zip)

**Comment by kkapsner** [comment]
... my profile is weird - the popup is back... but only sometimes.

Nevertheless I'm happy with the current situation. So I will so some more testing and then release the next version.

**Comment by jobisoft** [comment]
> Firefox has an API for webExtensions to react to these password popups.

Which one would that be?

**Comment by kkapsner** [comment]
> Which one would that be?

That would be https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onAuthRequired
Normal login forms have no API.
