### ISSUE TITLE
Add auto updata feature

### ISSUE THREAD

**Issue by kkapsner** [kkapsner/keepassxc-mail#7]
To keep the users up to date I should incorporate an auto update feature. I think the update_url entry in the manifest should also work in Thunderbird.

**Comment by acolomb** [comment]
Wouldn't it make more sense to use the existing Mozilla infrastructure and focus on #2 to have it in the official repository?

**Comment by kkapsner** [comment]
It would if I could do something useful there. Migrating the current state to a legacy addon is very time consuming and kind of for the bin as Thunderbird 78 will no longer support these. So at the moment I bank on the new API I requested...

In the meantime some automatic update would be nice and it should not be too complicated.
