### ISSUE TITLE
Need to re-establish Native Messaging every time I start TB

### ISSUE THREAD

**Issue by simonmarwitz** [kkapsner/keepassxc-mail#72]
When starting TB, password prompts appear and say "Loading passwords." for 30 seconds or more and then say "No passwords found.". Clicking retry immediately returns "No passwords found."

Then heading over to the keepassxc-mail preferences, the name of the connection and some kind of hash are displayed. Only after clicking "Reconnect to Native Messaging" the connection is properly established and passwords can be retrieved.

I reinstalled the plugin and also tried re-running the Linux commands to configure Native Messaging, but that did not help.

It used to work before I updated Thunderbird and Keepassxc last week (might have skipped over a few versions of TB, Keepass and the plugin).

I would be happy to provide some debugging data, I just don't know how to get it or what are the relevant parts to look for.

I am using keepassxc 2.7.1  and Thunderbird 102.2.2 (64-bit) with keepassxc-mail extension v. 1.1 (from addons.thunderbird.net) on openSUSE Tumbleweed Linux 5.19.8. (All packages were installed from the official openSUSE:Tumbleweed repository.)

**Comment by kkapsner** [comment]
This should not happen. Please try the latest version from #68 - it improves the startup.

If this still does not help you should open the console (Ctrl + Shift + J) and see if there is something useful.
Also you should look at the console of the extension (AddOns management -> click on the gear -> debug addons -> inspect keepassxc-mail -> console).

**Comment by simonmarwitz** [comment]
thank you, the linked version solved the problem.

**Comment by kkapsner** [comment]
Great to hear that. I will soon submit version 1.2 to [ATN](https://addons.thunderbird.net/de/thunderbird/addon/keepassxc-mail/) so it will be official then.
