### ISSUE TITLE
TB 102.3: Weird popup

### ISSUE THREAD

**Issue by Jonny007-MKD** [kkapsner/keepassxc-mail#74]
Hi,

Thanks again for your addon :)

My LMDE updated to TB 102.3 two days ago and I've got some issues. Thus, I am not quite sure whether it really is this addon's fault, and as most things don't work anyway I cannot say if it is only a display issue or something else. I've got this popup:

![image](https://user-images.githubusercontent.com/685945/193580444-1aaf2bf7-2e38-4f41-a199-70c4a07873fb.png)

This seems wrong :)

The addon is installed in version 1.2.

It did work before the update, and in KeePass these two accounts have different additional urls defined (as they are on different domains).

**Comment by Jonny007-MKD** [comment]
I have seen this quite a few times in these two days, so tell me if I can create some logs for you.

**Comment by kkapsner** [comment]
You can test this: [keepassxc-mail-1.2.1.zip](https://github.com/kkapsner/keepassxc-mail/files/9711365/keepassxc-mail-1.2.1.zip)

**Comment by Jonny007-MKD** [comment]
I don't see the dialog anymore. Probably that's a good sign? :) At least the above mentioned account was able to download mails right away.

Thanks!

**Comment by kkapsner** [comment]
If you have auto submit enabled the dialog does no longer show up (if everything works correctly) - see #68

I think I will submit this version to ATN.
