### ISSUE TITLE
Question: Correct way to setup keepassxc-mail entry manually

### ISSUE THREAD

**Issue by spamhater-grav** [kkapsner/keepassxc-mail#75]
Hi there, I am getting into your extension and keepass a bit more (thanks for your hardwork),

Just wondering how I am really supposed to set up an entry (or dual entry).
With most servers having two parts (will use this as an example) as an imap and smtp, I am supposed two entries one for the imap and one for the smtp in keepassxc - or is there way of combining this information into a single entry
Giving the below as an example. 

https://support.gmx.com/pop-imap/imap/server.html

Or is there a way to have one record and use the attributes way of including these items 

Many thanks

**Comment by ecoutinho** [comment]
Hi,

To have just one entry, on Keepassxc choose the imap entry, access "Browser Integration" and add the URL "smtp://mail.gmx.com". It will use the same authentication for both.

**Comment by kkapsner** [comment]
here some screenshots:
![grafik](https://user-images.githubusercontent.com/1105157/197561742-80b6e11d-7440-4d56-8d0c-c1c225b020c0.png)
![grafik](https://user-images.githubusercontent.com/1105157/197562139-bcfacdce-615d-494f-9bda-6e9c2245ddda.png)
