### ISSUE TITLE
Problems with Calendarentries

### ISSUE THREAD

**Issue by Postman589** [kkapsner/keepassxc-mail#76]
For me, the calendar entries from my provider are always not entered at Keepassxc. They always end up in the password store of Thunderbird. The entry has the form https://<url>:8443.
A manual entry did not work either. Somehow the entry always ends up where it doesn't belong. Is there anything you can do?
Thunderbird 102.4.0 Keepassxc 2.7.3

**Comment by kkapsner** [comment]
The URL seems weird.

What kind of calendar is it?
What is your provider?
Can you send me some screenshot of the calendar definition, the password prompts and the entry in the password store (please make sure all sensitive information is blurred)?

**Comment by kkapsner** [comment]
Without your input I'm not able to help you.

**Comment by kkapsner** [comment]
I will close this issue. If the problem persists and you provide the missing information I can reopen it.
