### ISSUE TITLE
No matching in pop-up windows

### ISSUE THREAD

**Issue by joebroesel** [kkapsner/keepassxc-mail#8]
Hi,

I could install the add-on in Linux (Ubuntu 19.10) following the installation instructions:
1. Installed and configured keepassxc-browser (I'm using this without error in Chrome and Firefox)
2. Copied the Native Messaging configuration
3. Started Thunderbird (68.4.1 (64-bit)), added the xpi (0.1.1) and got the key association request where I added a new unique name.
4. Added an entry with user/pass and URL: imap://<server> in KeePassXC

Everything seems to have worked, but I never get a  match for the server it seems. When the pop-up appears, I have to enter the password manually. What have I missed?

I get some errors in the Thunderbird Error Console (see Screenshot) right after installing the add-on.
![Screenshot_2020-03-03_17-23-50](https://user-images.githubusercontent.com/6543961/75796359-d25aa700-5d73-11ea-83d8-3a0a9498c8cf.png)

Any help appreciated! I would really love to use this add-on to get away from KeePass2 which I only use for Thunderbird.

**Comment by kkapsner** [comment]
There is a problem with a missing component of Thunderbird (wcap). I will release a new version soon that should fix that problem.

**Comment by kkapsner** [comment]
Should be fixed with 358714dae3436bf348d3844cdc494e7f092957a8

**Comment by kkapsner** [comment]
Please try https://github.com/kkapsner/keepassxc-mail/releases/tag/v0.1.2
