### ISSUE TITLE
Needs Update to TB 115

### ISSUE THREAD

**Issue by SevoStille** [kkapsner/keepassxc-mail#87]
## Steps to Reproduce (for bugs)

1. create a fresh Thunderbird profile
2. 
3. 
4. 

## Your Environment

* KeePassXC-mail version used:
* KeePassXC version:
* Thunderbird version:
* Operating system and version:

**Comment by kkapsner** [comment]
You should already be able to use it on 115 if you installed from ATN.

**Comment by kkapsner** [comment]
Version 1.6 is in review from Mozilla.

**Comment by Lgmrszd** [comment]
Hello, I have updated Thunderbird to 115.0 and the extension also got updated to 1.6 automatically. However, it seems like it stopped working. Thunderbird is prompting me to enter the password for the email profile and when provided, saves it to it's own password store.
(Just in case, KeePassXC version is 2.7.5)

**Comment by kkapsner** [comment]
Verson 1.6.1 is already submitted to ATN. In the meantime you can use https://github.com/kkapsner/keepassxc-mail/releases/tag/v1.6.1
