### ISSUE TITLE
Not working with Thunderbird nightly 117

### ISSUE THREAD

**Issue by kkapsner** [kkapsner/keepassxc-mail#88]
## Steps to Reproduce (for bugs)
1. create a fresh Thunderbird profile
2. add any account
3.  no password prompt is handled by KPM

## Your Environment
* KeePassXC-mail version used: 1.6
* Thunderbird version: 117

**Comment by kkapsner** [comment]
The dialog type for openpgp throws an error.

**Comment by kkapsner** [comment]
That's weird... it's working in TB 116 Beta...
Thanks for your offer to provide logs. But I will be able to test 115 tomorrow.

**Comment by mdonz** [comment]
I was going to add to this report that it is not working here for me on a fresh TB115 installation (on Ubuntu). I will monitor here to see your outcome of testing 115 before adding more details.

**Comment by kkapsner** [comment]
OK... please check if this works for you:
[keepassxc-mail-1.6.1.zip](https://github.com/kkapsner/keepassxc-mail/files/12065104/keepassxc-mail-1.6.1.zip)

**Comment by mdonz** [comment]
Oh, thanks. It seems to have fixed mail and CardDav access but not the CalDav (?). Will do more testing and come back with more details.

**Comment by kkapsner** [comment]
Can you please give me a screenshot from the CalDav password prompt?

**Comment by mdonz** [comment]
I had some calendar URLs wrong and confused myself with this. CalDAV calendars are working!
My apologies for misleading.

**Comment by kkapsner** [comment]
Version 1.6.1 is submitted to ATN
